# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-Makefile
version:      1.14
version_from: Makefile.pm
installdirs:  site
requires:
    GraphViz:                      0
    Make:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
