--- #YAML:1.0
name:               GraphViz-Makefile
version:            1.17
abstract:           Create Makefile graphs using GraphViz
author:
    - Slaven Rezic <srezic@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    GraphViz:  0
    Make:      0
resources:
    repository:  git://github.com/eserte/graphviz-makefile.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
